ドキュメントの修正
Tutorial-Inc/robotic-crowd-api-docs pull request #4
Opened 2022-03-16 03:27 UTC by ytatt

slackで依頼があった件の対応です。
https://tutorial-inc.slack.com/archives/CFCQ02TE2/p1647335322801849

確認できた箇所はすべて対応しましたので、他に修正すべき点があれば教えて下さい。

2022-03-16 06:08 UTC, chan-shiro reviewed
@ytatt ありがとうございます。

2022-03-16 06:09 UTC, chan-shiro commented
@ytatt 
途中で送信されてしまった。。。

ありがとうございます。いくつか確認したいこと質問しました。あと、トークンの作成方法ってあってます？

2022-03-16 10:48 UTC, ytatt commented on source/index.html.md
> -APIコール回数の制限は、組織単位で決定されており、ロボット1台につき 60回/分 となっております。
なくなっていませんが、ページ下部にh1見出しで同じようなことが書いてあったので、重複をなくすために削除しました。
<img width="892" alt="スクリーンショット 2022-03-16 19 47 57" src="https://user-images.githubusercontent.com/48622569/158573294-4afbe71c-c33c-40fa-a3b0-c1eed352f928.png">

2022-03-16 10:50 UTC, ytatt commented on source/index.html.md
> +echo -n '{"iss": "console.roboticcrowd.com","sub": "IjoiIiwiZ3JhbnRzIjp7Im","aud": "https://api.roboticcrowd.com/","nbf": 1450471147,"exp": 1450473747,"scopes": ["session_queue.write","session_queue.
実装側は文字列でしたので、修正しますね。
機能するjwtを作る意味では配列でも問題なかったです。

2022-03-16 10:53 UTC, ytatt commented
@chan-shiro 
> トークンの作成方法ってあってます？

ドキュメントを読みながら作成したjwtが普通に機能したので、合っているはずです。

2022-03-18 09:26 UTC, ytatt commented
@chan-shiro 
scopesを文字列で指定するよう変更しました！
ご確認お願いします。

2022-04-06 04:50 UTC, chan-shiro approved these changes
LGTM

2022-04-22 06:28 UTC, yusukeiwabuchi requested changes

2022-04-22 06:28 UTC, yusukeiwabuchi commented on source/index.html.md
> +| session_queue.delete | 実行キューを削除できます |
削除ではなくキャンセルではないでしょうか？
実際の処理は置いといて、言葉を揃えておいたほうが良いかと思いました。

<img width="593" alt="スクリーンショット 2022-04-22 15 26 47" src="https://user-images.githubusercontent.com/29683756/164616119-cea0052c-0604-4d5c-9757-e3cd5aa5c00f.png">

2022-04-22 07:26 UTC, ytatt commented on source/index.html.md
> +| session_queue.delete | 実行キューを削除できます |
@yusukeiwabuchi 
ありがとうございます。
`キャンセル`へ修正しました。

2022-04-25 06:00 UTC, yusukeiwabuchi approved these changes
LGTM

2022-04-26 10:50 UTC, merged